version: '3'
services:
  database:
    image: mysql:8
    container_name: shinhan-backend
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shinhan-backend